### PR TITLE
Bump django-large-image

### PR DESCRIPTION
**Pull request by banesullivan**
A few endpoints moved around. Rather than implementing a deprecated API for backward compatibility, I pushed the change out and I'm migrating all places where I know this broke myself

See https://github.com/girder/django-large-image/pull/30

### CODE REVIEW

**Review by annehaley — APPROVED** [review]
These changes are pretty straightforward. @naglepuff  are these the only instances where these endpoints are called?

**Comment by naglepuff** [comment]
@annehaley I tested this out locally, nothing appears to be broken. One question I have for @banesullivan though is what is the difference between `/tiles/metadata` and `/info/metadata`?

**Comment by banesullivan** [comment]
`/tiles/metadata` uses [`TileMetadataSerializer`](https://github.com/girder/django-large-image/blob/43c9ef62d83c4d6f33d3b49cc41f2c678f296584/django_large_image/rest/serializers.py#L4) giving a structured response of the tilesource's `.getMetadata()` (large-image method) with `levels`, `size_x`, `size_y`, `tile_size`, and `geospatial` while dumping any other metadata that the source yields into `additional_metadata`. 

`/info/metadata` returns the dict/json blob from the tilesource's `getMetadata()` method as is -- all those same fields but with the additional metadata at the top level rather than nested in the `additional_metadata` field.

Example Responses:

<table>
<tr>
<th>
<pre>
/tiles/metadata
</pre>
</th>
<th>
<pre>
/info/metadata
</pre>
</th>
</tr>

<tr>

<td>
<pre>
 {
  "levels": 6,
  "size_x": 4323,
  "size_y": 4323,
  "tile_size": 256,
  "geospatial": true,
  "additional_metadata": {
    "geospatial": true,
    "levels": 6,
    "sizeX": 4323,
    "sizeY": 4323,
    "sourceLevels": 6,
    "sourceSizeX": 4323,
    "sourceSizeY": 4323,
    "tileWidth": 256,
    "tileHeight": 256,
    "bounds": {
      "ll": {
        "x": -122.71879201711467,
        "y": 37.45219874192699
      },
      "ul": {
        "x": -122.71879201711467,
        "y": 38.052231141926995
      },
      "lr": {
        "x": -122.11875961711466,
        "y": 37.45219874192699
      },
      "ur": {
        "x": -122.11875961711466,
        "y": 38.052231141926995
      },
      "srs": "+proj=longlat +datum=WGS84 +no_defs",
      "xmin": -122.71879201711467,
      "xmax": -122.11875961711466,
      "ymin": 37.45219874192699,
      "ymax": 38.052231141926995
    },
    "sourceBounds": {
      "ll": {
        "x": -122.71879201711467,
        "y": 37.45219874192699
      },
      "ul": {
        "x": -122.71879201711467,
        "y": 38.052231141926995
      },
      "lr": {
        "x": -122.11875961711466,
        "y": 37.45219874192699
      },
      "ur": {
        "x": -122.11875961711466,
        "y": 38.052231141926995
      },
      "srs": "+proj=longlat +datum=WGS84 +no_defs",
      "xmin": -122.71879201711467,
      "xmax": -122.11875961711466,
      "ymin": 37.45219874192699,
      "ymax": 38.052231141926995
    },
    "bands": {
      "1": {
        "min": 5,
        "max": 255,
        "mean": 56.164648651261,
        "stdev": 45.505628098154,
        "interpretation": "red"
      },
      "2": {
        "min": 2,
        "max": 255,
        "mean": 61.590676043792,
        "stdev": 35.532493975171,
        "interpretation": "green"
      },
      "3": {
        "min": 1,
        "max": 255,
        "mean": 47.00898008224,
        "stdev": 29.470217162239,
        "interpretation": "blue"
      }
    },
    "magnification": null,
    "mm_x": 1381.876143450579,
    "mm_y": 1381.876143450579
  }
}
</pre>
</td>

<td>
<pre>
{
  "geospatial": true,
  "levels": 6,
  "sizeX": 4323,
  "sizeY": 4323,
  "sourceLevels": 6,
  "sourceSizeX": 4323,
  "sourceSizeY": 4323,
  "tileWidth": 256,
  "tileHeight": 256,
  "bounds": {
    "ll": {
      "x": -122.71879201711467,
      "y": 37.45219874192699
    },
    "ul": {
      "x": -122.71879201711467,
      "y": 38.052231141926995
    },
    "lr": {
      "x": -122.11875961711466,
      "y": 37.45219874192699
    },
    "ur": {
      "x": -122.11875961711466,
      "y": 38.052231141926995
    },
    "srs": "EPSG:4326",
    "xmin": -122.71879201711467,
    "xmax": -122.11875961711466,
    "ymin": 37.45219874192699,
    "ymax": 38.052231141926995
  },
  "sourceBounds": {
    "ll": {
      "x": -122.71879201711467,
      "y": 37.45219874192699
    },
    "ul": {
      "x": -122.71879201711467,
      "y": 38.052231141926995
    },
    "lr": {
      "x": -122.11875961711466,
      "y": 37.45219874192699
    },
    "ur": {
      "x": -122.11875961711466,
      "y": 38.052231141926995
    },
    "srs": "+proj=longlat +datum=WGS84 +no_defs",
    "xmin": -122.71879201711467,
    "xmax": -122.11875961711466,
    "ymin": 37.45219874192699,
    "ymax": 38.052231141926995
  },
  "bands": {
    "1": {
      "min": 5,
      "max": 255,
      "mean": 56.164648651261,
      "stdev": 45.505628098154,
      "interpretation": "red"
    },
    "2": {
      "min": 2,
      "max": 255,
      "mean": 61.590676043792,
      "stdev": 35.532493975171,
      "interpretation": "green"
    },
    "3": {
      "min": 1,
      "max": 255,
      "mean": 47.00898008224,
      "stdev": 29.470217162239,
      "interpretation": "blue"
    }
  },
  "magnification": null,
  "mm_x": 1381.876143450579,
  "mm_y": 1381.876143450579,
  "proj4": [
    "+proj=longlat +datum=WGS84 +no_defs"
  ],
  "frames": false
}
</pre>
</td>

</tr>
</table>

As you can tell, it is the same data. `tiles/metadata` provides the data in a predictable structure which you can use in the TS front-end where typing and all that fancy stuff requires this

The top-level fields in `/tiles/metadata` will always be there while much of the stuff included in `additional_metadata` may not always be there for different tile sources.

**Comment by naglepuff** [comment]
Great, thanks for the explanation!

**Pull request merged**
