### PR TITLE
Add a management command to dump the full django settings

### PR DESCRIPTION
**Pull request by waxlamp**
I jumped ahead and put this small management script together without looking too hard at whether there's a baked-in way to do it. Take a look and let me know what you think.

### CODE REVIEW

**Review by annehaley — APPROVED** [review]
I tried it and it works pretty well. :+1: However, if you're considering making this an upstream change for girder 4, perhaps a verbose vs quiet option for this command would be useful? This gives a lot of printout, and in many cases, I won't care about django default settings that haven't been overridden.

**Comment by waxlamp** [comment]
> I tried it and it works pretty well. +1 However, if you're considering making this an upstream change for girder 4, perhaps a verbose vs quiet option for this command would be useful? This gives a lot of printout, and in many cases, I won't care about django default settings that haven't been overridden.

I'm not sure how I could arrange to only show things that have been changed, since the way django-configurations works is to instantiate a class, run some hooks, and then slam all the uppercase attributes into the live config. Do you have any ideas?

**Comment by annehaley** [comment]
The [docs](https://docs.djangoproject.com/en/4.0/topics/settings/#:~:text=A%20Django%20settings%20file%20doesn%E2%80%99t%20have%20to%20define%20any%20settings%20if%20it%20doesn%E2%80%99t%20need%20to.%20Each%20setting%20has%20a%20sensible%20default%20value.%20These%20defaults%20live%20in%20the%20module%20django/conf/global_settings.py) say that the default settings are defined in `django.conf.global_settings.py`, so you could compare the output dict to the following:

```
from django.conf import global_settings

defaults = global_settings.__dict__
```

**Comment by waxlamp** [comment]
> The [docs](https://docs.djangoproject.com/en/4.0/topics/settings/#:~:text=A%20Django%20settings%20file%20doesn%E2%80%99t%20have%20to%20define%20any%20settings%20if%20it%20doesn%E2%80%99t%20need%20to.%20Each%20setting%20has%20a%20sensible%20default%20value.%20These%20defaults%20live%20in%20the%20module%20django/conf/global_settings.py) say that the default settings are defined in `django.conf.global_settings.py`, so you could compare the output dict to the following:
> 
> ```
> from django.conf import global_settings
> 
> defaults = global_settings.__dict__
> ```

Cool, thank you! I will try something out with this.

**Comment by waxlamp** [comment]
Of course this already exists. This command:

```
docker-compose run --rm django python ./manage.py diffsettings --output unified --all
```

does a very nice job of showing all settings together with the diff against the global defaults. Very handy, wish I knew about it before :)

**Pull request closed without merging**
