### PR TITLE
Make Dataset source uri nullable

### PR DESCRIPTION
**Pull request by annehaley**

### CODE REVIEW

**Comment by waxlamp** [comment]
@annehaley, if this closes an issue, could you reference it in the PR description?

**Comment by mcovalt** [comment]
What does it mean if a `Dataset` has no `content` and no `source_uri`?

**Comment by annehaley** [comment]
Hm, I think we want to prevent the creation of such Datasets. We can add a constraint that at least one of those fields is not null. I'll add it in this PR. [This](https://stackoverflow.com/questions/53085645/django-one-of-2-fields-must-not-be-null) suggests we do so in the `clean` method.

**Comment by mcovalt** [comment]
We should not use the `clean` method for validation. It is only used for Django's Forms API which we will not use. Instead, the constraint should be expressed [as a database constraint](https://docs.djangoproject.com/en/4.0/ref/models/constraints/#checkconstraint). A [validation check](https://www.django-rest-framework.org/api-guide/validators/) may also be included in the serializer.

**Review by mcovalt — APPROVED** [review]
Looks good. Thanks for the changes! It really helps me understand the data model through these constraints.

**Pull request merged**
