### PR TITLE
Show Vandy image in GeoJS

### LINKED ISSUE #46: Display Vandy data in an Investigation detail view
- Select a suitable image from Vandy Explorer
- coordinate with @marySalvi on how to import that data into the system
- Implement InvestigationDetail logic to show data via tile service

### PR DESCRIPTION
**Pull request by mcovalt**
- [x] add datasets to investigations in seed data
- [x] show dataset dropdown in investigation detail page
- [x] show new GeoJS map when dataset dropdown changes

### CODE REVIEW

**Comment by mcovalt** [comment]
Map should use [`geo.util.pixelCoordinateParams`](https://opengeoscience.github.io/geojs/apidocs/geo.util.html#.pixelCoordinateParams). A fetch to the image's tile metadata can provide the parameters.

**Comment by naglepuff** [comment]
Summary of changes up to and including 6576e63

**Server Changes:**
- Update `investigations.json` data and `populate.py` script to add `Dataset` objects to initial group of `Investigations`
- Update configuration `CORS_ALLOW_CREDENTIALS = TRUE` for `geojs`

**Client Changes**
- Update client-side TS types with most recent API changes
- Expand `vuex` store to include all of the current investigation's datasets (`currentDatasets`) and the dataset which should be displayed by the `geojs` map (`activeDataset`). New actions were included for setting these values.
- `useGeojs.ts` now watches for changes to the store's `activeDataset`. When a change is detected, the current map is torn down, and a new one is set up with a layer that points to the new `dataset`'s tile source
- `InvsetigationDetail.vue`now includes a select control to pick from available datasets to display in the main map. (Right now, changing the selection tears down the whole map and builds a new one with the newly selected dataset as the base layer). This could be improved by filtering for datasets of type `tile_source`. 
- `InvestigationList.vue`: changed the order that store actions are called. This is a minor UI improvement

**Comment by naglepuff** [comment]
@mcovalt 
I'm going to go ahead and mark this as ready for review. Feel free to convert back to draft if you disagree. 

**Testing Changes**

1. Re-run the `populate` script to get `Datasets` into your `Investigations`. 
2. Log in to the Atlascope front end. You'll be greeted by the same `InvestigationsList` view as before
3. Choose an Investigation to investigate. You'll once again be taken to the `InvestigationDetail` view
4. You should be looking at a whole slide image! There's also a select control at the top of the page that should show you the name of the `Dataset` you're looking at. Panning/zooming should be working as expected. (There's an automatic zoom that is scripted when the component gets mounted, this is a demonstration of how to use the `useGeojs` composable.)
5. Choose to investigate the "Whole Team Investigation." This has two datasets, and you should be able to toggle between them using the select control. As far as I can tell, these datasets have the same image. I've tested getting tiles from the swagger page as well and I get the same tile regardless of which `Dataset` ID I use.

**Comment by mcovalt** [comment]
@naglepuff This looks awesome! I can't approve my own PR, so I'll let someone else do that, then I'll merge.

**Comment by waxlamp** [comment]
> @naglepuff This looks awesome! I can't approve my own PR, so I'll let someone else do that, then I'll merge.

If it makes sense to do so, you can use your admin privilege to merge without a review. (In this case, for example, if Mike took over development and you are now "reviewing" his content despite formally being the author, that exception would apply.)

**Pull request merged**
